### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by somendrameena** [MarechJ/hll_rcon_tool#135]
I've been struggling with this issue since more than an year now. I've tried multiple libraries, even the official rcon library for Python, but I've got the same issue everytime.

## Server
I've a server for Counter Striker 1.6, running on AWS virtual machine. The installation was done following this article: https://linuxgsm.com/servers/csserver
The server is running fine, I'm able to play, run rcons as admin within game server, and even used HLSW for sending rcon commands remotely. All these works for me, but I'm not able to connect to my server using any of the rcon library.

## Logs
```
[2022-09-19 20:25:50,426][INFO] rcon.extended_commands extended_commands.py:connection_pool:86 | Initializing Rcon connection pool of size 20
[2022-09-19 20:26:05,062][ERROR] rcon manage.py:<module>:56 | Unexpected error.
Traceback (most recent call last):
  File "C:\somendra\learning\hll_rcon_tool\manage.py", line 44, in <module>
    from rcon.cli import cli, init
  File "C:\somendra\learning\hll_rcon_tool\rcon\cli.py", line 192, in <module>
    for name, func in inspect.getmembers(ctl):
  File "C:\Users\SMeena\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 351, in getmembers
    value = getattr(object, key)
  File "C:\Users\SMeena\AppData\Local\Programs\Python\Python39\lib\functools.py", line 993, in __get__
    val = self.func(instance)
  File "C:\somendra\learning\hll_rcon_tool\rcon\extended_commands.py", line 90, in connection_pool
    rcon._connect()
  File "C:\somendra\learning\hll_rcon_tool\rcon\commands.py", line 87, in _connect
    self.conn.connect(
  File "C:\somendra\learning\hll_rcon_tool\rcon\connection.py", line 27, in connect
    self.sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None)

Process finished with exit code 1
```

I'm sure I'm doing something wrong, or may be missing some major step.
This has become a major blocker for my project as this is the most important part. Can someone help me with this issue?

**Comment by timraay** [comment]
Hey, first off, this is a tool designed for Hell Let Loose, not Counter Strike. Even if you were to resolve the above connection error you would not be able to use this.

As for the actual error, as implied, the server you're attempting to connect to is refusing your connection. The IP address was found, but either no application is listening on the port you provided, or a firewall is preventing the connection. See [this comment](https://serverfault.com/a/725263) for more information.

If you want further support from us I'll have to ask you to ask for it in [our Discord](https://discord.gg/mXq6b4gRxT) instead, as this isn't a bug with our tool, but rather with how you've configured your server.

Lastly, as a side note, I don't think the RCON library you mentioned (I assume it's [this one](https://pypi.org/project/rcon/)?) is an official library. The only official libraries for creating socket connections are `socket` and `asyncio` (for asynchronous socket connections).

**Comment by somendrameena** [comment]
Apologies for placing the question at wrong place. I'll take help on the discord.
Thanks for your help @timraay
