### ISSUE TITLE
Upgrade error - Failed to initialized endpoints

### ISSUE THREAD

**Issue by kim-sondrup** [MarechJ/hll_rcon_tool#224]
After upgrading from v5.5.1 (8fbff08) to the latest v5.6.0 (9be36a9) I am having problems getting the backend/api to start.
I am still trying to debug the issue myself and will comment if I find anything, but in the meantime if anyone might have a solutions for the problems I am seeing then input it much welcome.

```
backend_1_1     | [2023-02-13 11:53:42,510][ERROR][undefined] rconweb views.py:<module>:714 | Failed to initialized endpoints - Most likely bad configuration
backend_1_1     | Traceback (most recent call last):
backend_1_1     |   File "/code/rconweb/api/views.py", line 695, in <module>
backend_1_1     |     for name, func in inspect.getmembers(ctl):
backend_1_1     |                       ^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/inspect.py", line 595, in getmembers
backend_1_1     |     return _getmembers(object, predicate, getattr)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/inspect.py", line 573, in _getmembers
backend_1_1     |     value = getter(object, key)
backend_1_1     |             ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
backend_1_1     |     val = self.func(instance)
backend_1_1     |           ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/code/rcon/recorded_commands.py", line 63, in connection_pool
backend_1_1     |     rcon._connect()
backend_1_1     |   File "/code/rcon/commands.py", line 86, in _connect
backend_1_1     |     self.conn.connect(
backend_1_1     |   File "/code/rcon/connection.py", line 29, in connect
backend_1_1     |     self.sock.connect((host, port))
backend_1_1     | TimeoutError: timed out
backend_1_1     | Traceback (most recent call last):
backend_1_1     |   File "/code/rconweb/./manage.py", line 21, in <module>
backend_1_1     |     main()
backend_1_1     |   File "/code/rconweb/./manage.py", line 17, in main
backend_1_1     |     execute_from_command_line(sys.argv)
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
backend_1_1     |     utility.execute()
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
backend_1_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
backend_1_1     |     self.execute(*args, **cmd_options)
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 393, in execute
backend_1_1     |     self.check()
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 419, in check
backend_1_1     |     all_issues = checks.run_checks(
backend_1_1     |                  ^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 76, in run_checks
backend_1_1     |     new_errors = check(app_configs=app_configs, databases=databases)
backend_1_1     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 13, in check_url_config
backend_1_1     |     return check_resolver(resolver)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 23, in check_resolver
backend_1_1     |     return check_method()
backend_1_1     |            ^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 416, in check
backend_1_1     |     for pattern in self.url_patterns:
backend_1_1     |                    ^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
backend_1_1     |     res = instance.__dict__[self.name] = self.func(instance)
backend_1_1     |                                          ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 602, in url_patterns
backend_1_1     |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
backend_1_1     |                        ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
backend_1_1     |     res = instance.__dict__[self.name] = self.func(instance)
backend_1_1     |                                          ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
backend_1_1     |     return import_module(self.urlconf_name)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_1_1     |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
backend_1_1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_1_1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_1_1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_1_1     |   File "/code/rconweb/rconweb/urls.py", line 21, in <module>
backend_1_1     |     path("api/", include("api.urls")),
backend_1_1     |                  ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/site-packages/django/urls/conf.py", line 34, in include
backend_1_1     |     urlconf_module = import_module(urlconf_module)
backend_1_1     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_1_1     |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
backend_1_1     |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
backend_1_1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_1_1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_1_1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_1_1     |   File "/code/rconweb/api/urls.py", line 5, in <module>
backend_1_1     |     from . import (
backend_1_1     |   File "/code/rconweb/api/scoreboards.py", line 32, in <module>
backend_1_1     |     from .views import _get_data, ctl
backend_1_1     |   File "/code/rconweb/api/views.py", line 695, in <module>
backend_1_1     |     for name, func in inspect.getmembers(ctl):
backend_1_1     |                       ^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/inspect.py", line 595, in getmembers
backend_1_1     |     return _getmembers(object, predicate, getattr)
backend_1_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/inspect.py", line 573, in _getmembers
backend_1_1     |     value = getter(object, key)
backend_1_1     |             ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
backend_1_1     |     val = self.func(instance)
backend_1_1     |           ^^^^^^^^^^^^^^^^^^^
backend_1_1     |   File "/code/rcon/recorded_commands.py", line 63, in connection_pool
backend_1_1     |     rcon._connect()
backend_1_1     |   File "/code/rcon/commands.py", line 86, in _connect
backend_1_1     |     self.conn.connect(
backend_1_1     |   File "/code/rcon/connection.py", line 29, in connect
backend_1_1     |     self.sock.connect((host, port))
backend_1_1     | TimeoutError: timed out
```
```
> docker image ls
REPOSITORY                 TAG       IMAGE ID       CREATED       SIZE
postgres                   12        2c278af658a7   2 days ago    373MB
redis                      latest    2f66aad5324a   4 days ago    117MB
postgres                   <none>    036cb848f092   4 days ago    373MB
maresh/hll_rcon_frontend   latest    828400a835f8   5 weeks ago   1.65GB
maresh/hll_rcon            latest    6396ad7d3676   5 weeks ago   1.38GB
```
```
> docker ps --format "table {{.Names}}\t{{.Image}}"
NAMES                          IMAGE
hll_rcon_tool_frontend_1_1     maresh/hll_rcon_frontend:latest
hll_rcon_tool_backend_1_1      maresh/hll_rcon:latest
hll_rcon_tool_supervisor_1_1   maresh/hll_rcon:latest
hll_rcon_tool_redis_1          redis:latest
hll_rcon_tool_postgres_1       postgres:12
```
```
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .env

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        db_data/

no changes added to commit (use "git add" and/or "git commit -a")
```
```
> git rev-parse HEAD
9be36a9c9b3fd6e33b30f24c8335e629dd40a505
```

**Comment by FlorianSW** [comment]
Why do you use some random commit from somewhere back in january? :) I would suggest to either use a released version (tag) or use the latest master version (including the hassle of upgrading more often than released versions).

In your case, it could be two possible issues, based on the error:
```
backend_1_1     |   File "/code/rcon/connection.py", line 29, in connect
backend_1_1     |     self.sock.connect((host, port))
backend_1_1     | TimeoutError: timed out
```
1. Your game server is offline or does not accept RCon connections from your server (where the RCon tool is hosted). This is a network error, so not something like a wrong password or such.
2. It's an issue with the newly introduced connection pool

If it is the first one, you should most likely have issues with that before already, which would indicate that it is 1. If it is the second, you should really checkout the latest master version. There were couple of adjustments, improvements and bug fixes for the connection handling after the commit you mentioned. Or, alternatively, rollback to the latest released version.

**Comment by MarechJ** [comment]
Closing as this is more of a "tech support" topic for Discord
