### ISSUE TITLE
PostgreSQL Errors in api.log

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#494]
Getting the following error from api.log

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/rconweb/api/views.py", line 143, in public_info
    config = RconServerSettingsUserConfig.load_from_db()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/rcon/user_config/utils.py", line 95, in load_from_db
    conf = get_user_config(cls.KEY(), default=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/rcon/user_config/utils.py", line 145, in get_user_config
    res = _get_conf(sess, key)
          ^^^^^^^^^^^^^^^^^^^^
  File "/code/rcon/user_config/utils.py", line 138, in _get_conf
    sess.rollback()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1931, in rollback
    self._transaction.rollback(_to_root=True)
  File "<string>", line 2, in rollback
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1338, in rollback
    raise rollback_err[1].with_traceback(rollback_err[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1303, in rollback
    t[1].rollback()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2599, in rollback
    self._do_rollback()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2718, in _do_rollback
    self._close_impl(try_deactivate=True)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2701, in _close_impl
    self._connection_rollback_impl()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2693, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1121, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1119, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 692, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```

**Comment by cemathey** [comment]
I've never seen that one before. Do you have any more details, what you were doing when it happened, what version of CRCON were you on at the time? Are there any steps you can take to reliably reproduce it?

**Comment by LordofAgents** [comment]
@jordantrizz We do not have enough information from you to determine the issue. If you also have the issues, please open another issue or provide the necessary information needed.

**Comment by jordantrizz** [comment]
All good, was a long time ago and I don't host a hll_rcon_tool instance anymore.
